# Generated by Django 4.1.4 on 2023-02-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="Bio",),
        migrations.RemoveField(model_name="profile", name="DP",),
        migrations.RemoveField(model_name="profile", name="Nickname",),
    ]
