# Generated by Django 4.1.4 on 2023-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_remove_profile_bio_remove_profile_dp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="DP",
            field=models.ImageField(default="default.png", upload_to="profile_pics"),
        ),
    ]
