# Generated by Django 4.1.4 on 2023-03-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_profile_dp"),
    ]

    operations = [
        migrations.RenameField(model_name="profile", old_name="DP", new_name="image",),
    ]
