# Generated by Django 4.1.4 on 2023-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookie_flavor", models.CharField(max_length=50)),
                ("available_stock", models.BooleanField(verbose_name="In Stock")),
            ],
        ),
    ]
