# Generated by Django 4.1.4 on 2023-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0003_alter_cakes_cake_type_alter_cookies_cookie_flavor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookies", name="available_stock", field=models.BooleanField(),
        ),
    ]
