# Generated by Django 4.1.4 on 2023-02-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0004_alter_cookies_available_stock"),
    ]

    operations = [
        migrations.RenameModel(old_name="Cakes", new_name="Caakes",),
    ]
