# Generated by Django 4.1.4 on 2023-02-18 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0005_rename_cakes_caakes"),
    ]

    operations = [
        migrations.RemoveField(model_name="caakes", name="available_stock",),
        migrations.AddField(
            model_name="caakes",
            name="Best_Before",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="caakes",
            name="availability",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
