# Generated by Django 4.1.4 on 2023-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "delight_Cakehouse",
            "0006_remove_caakes_available_stock_caakes_best_before_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="caakes",
            name="availability",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caakes",
            name="cake_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
