# Generated by Django 4.1.4 on 2023-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0007_alter_caakes_availability_alter_caakes_cake_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="caakes",
            name="in_stock",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
