# Generated by Django 4.1.4 on 2023-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0012_alter_caakes_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caakes",
            name="Image",
            field=models.ImageField(
                default="default.jpg",
                upload_to="home/marwa254/Desktop/DELIGHT/mysite/delight_Cakehouse/images",
            ),
        ),
    ]
