# Generated by Django 4.1.4 on 2023-03-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0013_alter_caakes_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caakes", old_name="in_stock", new_name="In_stock",
        ),
    ]
