# Generated by Django 4.1.4 on 2023-03-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0014_rename_in_stock_caakes_in_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caakes", old_name="In_stock", new_name="in_stock",
        ),
    ]
