# Generated by Django 4.1.4 on 2023-03-11 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0015_rename_in_stock_caakes_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caakes",
            name="Best_Before",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
