# Generated by Django 4.1.4 on 2023-03-11 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delight_Cakehouse", "0016_alter_caakes_best_before"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caakes",
            name="Best_Before",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
